Fix the issue with frontstage failure
ONSdigital/rm-case-service pull request #167
Opened 2020-12-22 15:43 UTC by akssinhaamit

# Motivation and Context
While creating the active-enrolment field the default constraint was not set due to which when the Front stage looks for old cases it fails in preprod with null value.
# What has changed

# How to test?

# Links

2020-12-23 09:40 UTC, jterryons requested changes

2020-12-23 09:40 UTC, jterryons commented on src/main/resources/database/changelog-master.yml
> +      file: database/changes/release-24/changelog.yml
release-25

2020-12-23 11:30 UTC, akssinhaamit commented on src/main/resources/database/changelog-master.yml
> +      file: database/changes/release-24/changelog.yml
done

2020-12-23 11:31 UTC, akssinhaamit commented on src/main/resources/database/changelog-master.yml
> +      file: database/changes/release-24/changelog.yml
the next one would be release-25

2021-01-04 15:12 UTC, insacuri approved these changes

2021-01-04 16:30 UTC, merged