Remove Rabbit and Spring integration xml
ONSdigital/rm-case-service pull request #219
Opened 2021-09-10 14:19 UTC by warrenbailey

# What and why?

# How to test?

# Trello

2021-09-10 14:34 UTC, warrenbailey commented
/deploy baileyw

2021-09-13 08:22 UTC, warrenbailey commented
/deploy baileyw

2021-09-14 13:22 UTC, insacuri requested changes
One super small comment, but looks good

2021-09-14 13:22 UTC, insacuri commented
/deploy manna

2021-09-14 14:02 UTC, warrenbailey commented on _infra/helm/case/Chart.yaml
> +version: 11.1.54
good shout

2021-09-14 15:23 UTC, insacuri approved these changes

2021-09-14 15:48 UTC, merged